"#include \"FamilyLegacySystem.h\"\n"
"#include <iostream>\n"
"\n"
"// ----- Trait Implementation -----\n"
"Trait::Trait(std::string name, std::string description, int legacyImpact)\n"
"    : name(name), description(description), legacyImpact(legacyImpact) {}\n"
"\n"
"void Trait::applyToSim(Sim* sim) {\n"
"    std::cout << \"Applying trait '\" << name << \"' to Sim.\\n\";\n"
"}\n"
"\n"
"int Trait::getLegacyModifier() const {\n"
"    return legacyImpact;\n"
"}\n"
"\n"
"// ----- Sim Implementation -----\n"
"Sim::Sim(std::string name, int age)\n"
"    : name(name), age(age), legacyScore(0) {}\n"
"\n"
"void Sim::ageUp() {\n"
"    age++;\n"
"    std::cout << name << \" has aged up to \" << age << \" years old.\\n\";\n"
"}\n"
"\n"
"int Sim::getLegacyScore() const {\n"
"    return legacyScore;\n"
"}\n"
"\n"
"void Sim::interactWith(Sim* otherSim) {\n"
"    std::cout << name << \" interacts with \" << otherSim->name << \".\\n\";\n"
"}\n"
"\n"
"void Sim::passOnTraits() {\n"
"    std::cout << name << \" is passing on traits to their child.\\n\";\n"
"}\n"
"\n"
"void Sim::addTrait(const Trait& trait) {\n"
"    traits.push_back(trait);\n"
"    legacyScore += trait.getLegacyModifier();\n"
"    std::cout << \"Trait added to \" << name << \": \" << trait.getLegacyModifier() << \" legacy points.\\n\";\n"
"}\n"
"\n"
"void Sim::addAchievement(const Achievement&) {\n"
"    // Empty for now\n"
"}\n"
"\n"
"void Sim::addRelationship(Relationship*) {\n"
"    // Empty for now\n"
"}\n"
""